server:
  port: 8200
spring:
  application:
    name: user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            # 线程超时15秒,调用Fallback方法
            timeoutInMilliseconds: 2000